# -*- coding: utf-8 -*-
"""covid_visualization_updated.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFntWy26ckrZX55jzwYsQfUuS-Z8AFoy
"""

import requests
import pandas as pd
import matplotlib.pyplot as plt

# Fetch data from COVID-19 API
url = "https://api.covid19api.com/summary"
response = requests.get(url)
data = response.json()

# Extract global and country-specific data
global_data = data['Global']
countries_data = data['Countries']

# Convert countries data to a DataFrame
df = pd.DataFrame(countries_data)

# Filter data for PH and DEU
focus_countries = df[df['CountryCode'].isin(['PH', 'DE'])]

# Create visuals folder if not exists
import os
os.makedirs('./visuals', exist_ok=True)

# Line chart for PH and DEU cases over time
plt.figure(figsize=(10, 6))
plt.bar(focus_countries['Country'], focus_countries['TotalConfirmed'], label='Total Cases')
plt.bar(focus_countries['Country'], focus_countries['TotalDeaths'], label='Total Deaths', alpha=0.7)
plt.title('COVID-19 Cases and Deaths: PH vs DEU')
plt.xlabel('Country')
plt.ylabel('Counts')
plt.legend()
plt.savefig('./visuals/ph_deu_cases_deaths.png')
plt.show()

# Bar chart for top 5 countries by cases
top_5_countries = df.nlargest(5, 'TotalConfirmed')
plt.figure(figsize=(10, 6))
plt.bar(top_5_countries['Country'], top_5_countries['TotalConfirmed'], color='orange')
plt.title('Top 5 Countries by COVID-19 Cases')
plt.xlabel('Country')
plt.ylabel('Total Cases')
plt.savefig('./visuals/top_5_cases.png')
plt.show()

# Save global summary as a text file
with open('./visuals/global_summary.txt', 'w') as f:
    f.write("Global COVID-19 Summary:\n")
    f.write(f"Total Cases: {global_data['TotalConfirmed']}\n")
    f.write(f"Total Deaths: {global_data['TotalDeaths']}\n")
    f.write(f"Total Recovered: {global_data['TotalRecovered']}\n")